osx_image: xcode8
language: objective-c
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./swiftlint.sh; fi
script:
  - xcodebuild clean build -project Aftermath.xcodeproj -scheme Aftermath-iOS -sdk iphonesimulator
  - xcodebuild test -project Aftermath.xcodeproj -scheme Aftermath-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
  - xcodebuild clean build -project Aftermath.xcodeproj -scheme Aftermath-Mac -sdk macosx
  - xcodebuild test -project Aftermath.xcodeproj -scheme Aftermath-Mac -sdk macosx
  - xcodebuild clean build -project Aftermath.xcodeproj -scheme "Aftermath-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0'
  - xcodebuild test -project Aftermath.xcodeproj -scheme "Aftermath-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0'
notifications:
  email: false
